name: Terraform CD

on:
  push:
    branches:
      - feature

permissions:
  contents: read

jobs:
  terraform-cd:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"4f643487-2a9f-4340-8c17-af429ba67805","clientSecret":"fc780bf3-3811-4036-baaa-349a88f419d1","subscriptionId":"4bdb1173-0046-44b6-8053-eb1416c8b631
","tenantId":"278882f4-f5ef-49fd-94c7-e9c92e6cab9b"}'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
